language: python
python:
  - "3.5"
  - "3.6"
  - "3.7.11"
  - "3.8"
install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install -r requirements.txt
  - pip install urllib3==1.26.6
script:
  - coverage run -m unittest discover
after_success:
  - coveralls
